# Use root/example as user/password credentials
version: '3.1'

services:

  api:
    build: .
    container_name: patient-service
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      MySql__CONNECTIONSTRING: "Server=db;Port=3306;Database=test;Uid=root;Pwd=example;"
  db:
    ports:
        - "3306:3306"
    container_name: mysql-local
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
          - "./my-init-scripts/init.sql:/docker-entrypoint-initdb.d/1.sql"
    # (this is just an example, not intended to be a production configuration)